[package]
name = "h3"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.78.0", features = ["quinn"] }
tokio = { version = "1.45.0", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
